### ISSUE TITLE
Policy has a confusing purpose

### ISSUE THREAD

**Issue by tomhukins** [bluefeet/Perl-Critic-Policy-Moo-ProhibitMakeImmutable#3]
Hi, this `Perl::Critic` policy confuses me.  Its documentation states that calling `make_immutable` on a Moo class
> triggers Moose to be loaded and metaclass created, which defeats some of the benefits you get using Moo instead of Moose

However, [Moo's documentation](https://metacpan.org/pod/Moo#meta) describes the meta method as returning an object that calling
> anything other than make_immutable on it, the object will be transparently upgraded to a genuine Moose::Meta::Class instance, loading Moose

So, I would expect a useful policy to warn about calls to anything other than `make_immutable` on objects returned by `Moo->meta`: the opposite of this policy's behaviour.

What do you think?

**Comment by bluefeet** [comment]
You know what, I think the behavior must of changed, especially with this comment in the Moo docs:

> `make_immutable` itself is a no-op, since we generate metaclasses that are already immutable, and users converting from Moose had an unfortunate tendency to accidentally load Moose by calling it.

So, sounds like `make_immutable()` used to load Moose right off the bat, and since then they moved that to `meta()`.  I wasn't able to confirm that with git or the changes file.

So, ya, this policy isn't nearly as useful as it once was.  Sounds like a new policy may be in order.

> So, I would expect a useful policy to warn about calls to anything other than make_immutable on objects returned by Moo->meta: the opposite of this policy's behaviour.

I don't see how that's "opposite" behavior, far from, its just different behavior and less useful.  Opposite behavior from this module would be something that warned when people didn't call make_immutable on Moo classes.

**Comment by tomhukins** [comment]
> You know what, I think the behavior must of changed
That didn't occur to me, but it explains why I found the policy so confusing. :)

**Comment by bluefeet** [comment]
7717e172584ba5cb18f3db6257e03e73745dbb7e

**Comment by bluefeet** [comment]
It may be the behavior never changed and the documentation was just wrong, hard to tell.

**Comment by bluefeet** [comment]
0.06 should be hitting CPAN shortly.  Thank you!
